Draft: Retry timed out requests from request
turt2live/matrix-bot-sdk pull request #185
Opened 2021-12-16 17:53 UTC by Gnuxie

Hey, I'm not really sure what I'm doing. This is a first draft and I've gone with what I feel like is the least intrusive and simplest solution, I'll be really happy to change this if there is a better way to go about it.

My reason for submitting this PR is to make [Mjolnir](https://matrix.org/matrix-org/mjolnir) a little more resilient to longer requests in the bigger rooms. One thing that is important in this regard is being able to notify of a slow request when the request is the result of a command. We also think in Mjolnir's case some requests should fail sooner than later because of time sensitivity of some commands in their response to abuse. In this PR we emit an event on the MatrixClient's event emitter when a request is about to be retried so that we can handle both of these points.

I could have wrapped the request function and implemented it all from Mjolnir using `http.ts`'s `setRequestFn` but this would make handling the two constraints I mentioned a little bit less ergonomic and it would mean other user's of matrix-bot-sdk wouldn't be able to use the solution, if there is a demand for that? I will do this as a backup plan though.

Relevant but slightly out of date now: https://github.com/turt2live/matrix-bot-sdk/issues/18#issuecomment-990052384

2022-01-06 10:35 UTC, Yoric commented on src/MatrixClient.ts
> +            return 1.6 ** nRetries * timeout;
Nit: Feels that this `1.6` should be a named constant (or a parameter).

2022-01-06 11:04 UTC, Yoric requested changes
Note: I can't approve a PR on this project because I'm not a dev on it.

But I can make a first pass of review :)

2022-01-06 11:04 UTC, Yoric commented on src/MatrixClient.ts
> +let clientRequestId = 0;
You're going to get race conditions reading this. You need to capture the value when you start `doRequest` if you wish to be consistent.

2022-04-09 04:32 UTC, turt2live commented
@Gnuxie is this still a draft, and are you able to take a look at the conflicts?

2022-10-07 04:39 UTC, turt2live commented
Closing as the changes appear to be abandoned - please open a new PR if needed.

2022-10-07 04:39 UTC, closed without merging